### ISSUE TITLE
Not working with a seeeduino lorawan board

### ISSUE THREAD

**Issue by ronniesa** [Seeed-Studio/Grove-Ranging-sensor-VL53L0X#1]
I tried to make the Time of Flight grove sensor work with a Seeeduino LoRaWAN board without success.
I tried various samples and none works. The code never comes back from a VL53L0X.Pefrom….. call. 

For example in the single_ranging.ino it arrives until this line “Status=VL53L0X.PerformSingleRangingMeasurement(&RangingMeasurementData);” and never comes back.

**Comment by linux-downey** [comment]
> I tried to make the Time of Flight grove sensor work with a Seeeduino LoRaWAN board without success.
> I tried various samples and none works. The code never comes back from a VL53L0X.Pefrom….. call.
> 
> For example in the single_ranging.ino it arrives until this line “Status=VL53L0X.PerformSingleRangingMeasurement(&RangingMeasurementData);” and never comes back.

Thanks for your feedback.The previous version is not compatible with SAMD platform,I am sorry for causing trouble to you.I have fixed it,please check it.
    Best regards
    downey

**Comment by ronniesa** [comment]
Tested the new version and it works. Thx a lot
