### ISSUE TITLE
Add to Arduino library manager

### ISSUE THREAD

**Issue by jimbobbennett** [Seeed-Studio/Grove-Ranging-sensor-VL53L0X#3]
I've been searching for this in the Arduino library manager, and can't find it. Can you raise the relevant pull request to add this please.

Instructions are here: https://github.com/arduino/library-registry#readme

Let me know if you are happy for me to do this.

**Comment by haiershu** [comment]
Hello, I will submit this library to Arduino within today

**Comment by jimbobbennett** [comment]
I can see this in the library manager in the Arduino IDE and PlatformIO now. Thanks @haiershu!
