### ISSUE TITLE
high_speed_ranging.ino 

### ISSUE THREAD

**Issue by courtens** [Seeed-Studio/Grove-Ranging-sensor-VL53L0X#5]
What are the absolute minimum requirements to make to code run (the fastest)?

I am hoping to control a motor with the same Seeeduino, if possible. (Probably not a good idea to do it on the same chip.) 

Adding more comments/notes to the code would really help.

Thank you.

**Comment by ackPeng** [comment]
@courtens This may involve multiple aspects. Do you still have this doubt?

**Comment by Lesords** [comment]
Hello,

I\'m going to close this issue, feel free to re-open it if you have any other questions.

[Autocommentary]
